# Configuration file

  accelerator {
    B:enable=true
    I:max_particle_bunches=20
}


    alfo_skybox {
    S:skybox_id=alfo
}


    breathing {
    I:air_generation_interval_ticks=40
    I:air_generation_range_blocks <
    200
    16
    48
    144
    >
    I:air_tank_breath_duration_ticks=300
    I:air_tank_capacity_by_tier <
    20
    32
    64
    128
    >
    B:enable_air_at_entity_debug=false
    I:energy_per_canister=200
    I:energy_per_existing_air_block_by_tier <
    0
    4
    60
    870
    >
    I:energy_per_new_air_block_by_tier <
    0
    12
    180
    2610
    >
    I:max_energy_stored_by_tier <
    0
    1400
    21000
    304500
    >
    I:simulation_delay_ticks=30
    I:volume_update_depth_blocks=256
}


    capacitor {
    D:efficiency_per_upgrade <
    0.95
    0.98
    1.0
    >
    I:flux_rate_input_per_tick_by_tier <
    1073741823
    800
    4000
    20000
    >
    I:flux_rate_output_per_tick_by_tier <
    1073741823
    800
    4000
    20000
    >
    S:ic2_sink_tier_name_by_tier <
    MaxV
    MV
    HV
    EV
    >
    S:ic2_source_tier_name_by_tier <
    MaxV
    MV
    HV
    EV
    >
    I:max_energy_stored_by_tier <
    20000000
    800000
    4000000
    20000000
    >
}


    chunk_loader {
    I:energy_per_chunk=8
    I:max_energy_stored=1000000
    I:max_radius=2
}


    client {
    B:breathing_overlay_forced=true
    S:location_background_color=0x40303030
    B:location_has_shadow=true
    S:location_name_prefix=§l
    I:location_offset_x=0
    I:location_offset_y=-20
    D:location_scale=1.0
    S:location_screen_alignment=MIDDLE_RIGHT
    S:location_text_alignment=TOP_RIGHT
    S:location_text_color=0xE6B4B4F0
    I:location_width_min=90
    D:location_width_ratio=0.0
}


    cloaking {
    I:coil_capture_blocks=5
    I:field_refresh_interval_seconds=3
    I:max_energy_stored=500000000
    I:max_field_radius=63
    I:tier1_energy_per_block=32
    I:tier2_energy_per_block=128
}


    enantiomorphic_reactor {
    I:max_energy_stored_by_tier <
    100000000
    100000000
    500000000
    2000000000
    >
    I:max_generation_RF_by_tier <
    64000
    64000
    192000
    576000
    >
    I:max_lasers <
    64
    6
    12
    24
    >
    I:min_generation_RF_by_tier <
    4
    4
    4
    4
    >
}


    energy {
    S:display_units=RF
    B:enable_FE=true
    B:enable_GTCE_EU=true
    B:enable_IC2_EU=true
    B:enable_RF=true
    D:overvoltage_explosion_factor=1.0
    D:overvoltage_shock_factor=1.0
    I:scan_interval_ticks=20
}


    force_field {
    D:explosion_strength_vanilla_cap=15.0
    D:projector_explosion_scale=1000.0
    I:projector_max_energy_stored_by_tier <
    20000000
    30000
    90000
    150000
    >
    D:projector_max_laser_required=10.0
}


    general {
    I:assembly_scanning_interval=10
    D:blast_resistance_cap=60.0
    I:blocks_per_tick=3500
    B:enable_experimental_refresh=false
    B:enable_fast_set_blockstate=false
    B:enable_forge_chunk_manager=true
    B:enable_protection_checks=true
    B:enforce_valid_celestial_objects=true
    I:entity_NPC_id=246
    I:entity_camera_id=243
    I:entity_laser_exploder_id=245
    I:entity_offline_avatar_id=247
    I:entity_particle_bunch_id=244
    I:entity_seat_id=248
    I:entity_sphere_generator_id=241
    I:entity_star_core_id=242
    I:hyperspace_provider_id=15
    I:lua_scripts=2
    I:minimum_dimension_unload_queue_delay_ticks=100
    I:parameters_update_interval=20
    I:registry_update_interval=10
    S:schematics_location=warpDrive_schematics
    I:space_biome_id=95
    I:space_provider_id=14
}


    ic2_reactor_laser {
    I:component_heat_transfer_per_tick=54
    I:cooling_interval_ticks=10
    I:cooling_per_interval=1080
    D:energy_per_heat=2.0
    I:focus_heat_transfer_per_tick=648
    I:max_heat_stored=30000
    I:reactor_heat_transfer_per_tick=54
}


    jump_gate {
    I:size_max_per_side_by_tier <
    127
    32
    64
    127
    >
}


    laser_cannon {
    D:block_hit_absorption_max=0.8
    D:block_hit_absorption_per_block_hardness=0.01
    I:block_hit_energy_max=750000
    I:block_hit_energy_min=75000
    I:block_hit_energy_per_block_hardness=150000
    D:block_hit_explosion_base_strength=8.0
    I:block_hit_explosion_energy_per_strength=125000
    D:block_hit_explosion_hardness_threshold=5.0
    D:block_hit_explosion_max_strength=50.0
    D:booster_beam_energy_efficiency=0.6
    I:emit_fire_delay_ticks=5
    I:emit_scan_delay_ticks=1
    D:energy_attenuation_per_air_block=2.0E-4
    I:entity_hit_base_damage=3
    I:entity_hit_energy=15000
    I:entity_hit_energy_per_damage=30000
    I:entity_hit_energy_threshold_for_explosion=900000
    D:entity_hit_explosion_base_strength=4.0
    I:entity_hit_explosion_energy_per_strength=125000
    D:entity_hit_explosion_max_strength=4.0
    I:entity_hit_max_damage=100
    I:entity_hit_set_on_fire_seconds=20
    I:max_laser_energy=3400000
    I:max_mediums_count=10
    I:range_max=500
}


    laser_medium {
    D:bonus_factor_by_tier <
    1.25
    0.5
    1.0
    1.5
    >
    I:max_energy_stored_by_tier <
    1000000
    10000
    30000
    100000
    >
}


    lift {
    I:energy_per_entity=150
    I:entity_cooldown_ticks=40
    I:max_energy_stored=900
    I:update_interval_ticks=10
}


    logging {
    B:enable_LUA_logs=false
    B:enable_XML_preprocessor_logs=false
    B:enable_accelerator_logs=false
    B:enable_break_place_logs=false
    B:enable_breathing_logs=false
    B:enable_building_logs=false
    B:enable_camera_logs=false
    B:enable_chunk_handler_logs=false
    B:enable_chunk_loading_logs=true
    B:enable_client_synchronization_logs=false
    B:enable_cloaking_logs=false
    B:enable_collection_logs=false
    B:enable_dictionary_logs=false
    B:enable_effects_logs=false
    B:enable_energy_logs=false
    B:enable_entity_fx_logs=false
    B:enable_force_field_logs=false
    B:enable_force_field_registry_logs=false
    B:enable_global_region_registry_logs=false
    B:enable_gravity_logs=false
    B:enable_jump_logs=true
    B:enable_jumpblocks_logs=false
    B:enable_offline_avatar_logs=true
    B:enable_profiling_CPU_time=true
    B:enable_profiling_memory_allocation=false
    B:enable_profiling_thread_safety=false
    B:enable_radar_logs=false
    B:enable_rendering_logs=false
    B:enable_targeting_logs=false
    B:enable_transporter_logs=false
    B:enable_videoChannel_logs=false
    B:enable_weapon_logs=false
    B:enable_world_generation_logs=false
    D:throttle_ms=5000.0
}


    mining_laser {
    I:max_mediums_count=3
    I:mine_delay_ticks=3
    I:mine_energy_per_block_in_atmosphere=2500
    I:mine_energy_per_block_in_void=1500
    D:mine_ores_only_energy_factor=15.0
    D:mine_silktouch_energy_factor=1.5
    I:radius_no_laser_medium=4
    I:radius_per_laser_medium=1
    I:scan_delay_ticks=20
    I:scan_energy_per_layer_in_atmosphere=30000
    I:scan_energy_per_layer_in_void=20000
    I:warmup_delay_ticks=20
}


    offline_avatar {
    B:always_render_name_tag=false
    B:create_only_aboard_ships=true
    I:delay_for_removal_s=1
    B:enable=true
    B:forget_on_death=false
    D:max_range_for_removal=5.0
    D:min_range_for_removal=1.0
    D:model_scale=0.5
}


    radar {
    D:factors_energy_cost <
    0.0
    0.0
    0.0
    1.0E-4
    >
    I:max_energy_stored=100000000
    I:max_isolation_blocks=16
    D:max_isolation_effect=1.0
    I:max_isolation_range=2
    I:min_energy_cost=10000
    I:min_isolation_blocks=2
    D:min_isolation_effect=0.12
    D:scan_delay_factors_seconds <
    1.0
    0.001
    0.0
    0.0
    >
    I:scan_min_delay_seconds=1
}


    ship {
    I:collision_tolerance_blocks=3
    I:mass_max_by_tier <
    2000000
    3456
    13824
    110592
    >
    I:mass_min_by_tier <
    0
    64
    1728
    6912
    >
    S:mass_unlimited_player_names <
    notch
    someone
    >
    I:max_energy_stored_by_tier <
    0
    500000
    10000000
    100000000
    >
    I:size_max_per_side_by_tier <
    127
    24
    48
    96
    >
    I:volume_max_on_planet_surface=3000
    I:volume_min_for_hyperspace=4000
    I:volume_scan_age_tolerance=120
    I:volume_scan_blocks_per_tick=1000
    I:warmup_random_ticks=60
}


    ship_movement_costs {
    D:gate_activating_cooldown_interval_seconds <
    20.0
    0.0
    0.0
    0.0
    0.0
    >
    D:gate_activating_energyRequired_factors <
    20000.0
    10.0
    100.0
    0.0
    0.0
    >
    D:gate_activating_max_jump_distance <
    100000.0
    0.1
    0.0
    0.0
    0.0
    >
    D:gate_activating_sickness_seconds <
    3.0
    0.0
    0.0
    0.0
    0.0
    >
    D:gate_activating_warmup_seconds <
    10.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_entering_cooldown_interval_seconds <
    60.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_entering_energyRequired_factors <
    1.0E7
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_entering_max_jump_distance <
    100.0
    0.1
    0.0
    0.0
    0.0
    >
    D:hyperspace_entering_sickness_seconds <
    10.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_entering_warmup_seconds <
    40.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_exiting_cooldown_interval_seconds <
    60.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_exiting_energyRequired_factors <
    1.0E7
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_exiting_max_jump_distance <
    100.0
    0.1
    0.0
    0.0
    0.0
    >
    D:hyperspace_exiting_sickness_seconds <
    10.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_exiting_warmup_seconds <
    40.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_moving_cooldown_interval_seconds <
    30.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_moving_energyRequired_factors <
    10000.0
    1.0
    10.0
    0.0
    0.0
    >
    D:hyperspace_moving_max_jump_distance <
    200.0
    0.5
    0.0
    0.0
    0.0
    >
    D:hyperspace_moving_sickness_seconds <
    10.0
    0.0
    0.0
    0.0
    0.0
    >
    D:hyperspace_moving_warmup_seconds <
    20.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_landing_cooldown_interval_seconds <
    60.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_landing_energyRequired_factors <
    10000.0
    10.0
    100.0
    0.0
    0.0
    >
    D:planet_landing_max_jump_distance <
    50.0
    0.1
    0.0
    0.0
    0.0
    >
    D:planet_landing_sickness_seconds <
    0.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_landing_warmup_seconds <
    20.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_moving_cooldown_interval_seconds <
    40.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_moving_energyRequired_factors <
    100.0
    10.0
    100.0
    0.0
    0.0
    >
    D:planet_moving_max_jump_distance <
    50.0
    0.1
    0.0
    0.0
    0.0
    >
    D:planet_moving_sickness_seconds <
    0.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_moving_warmup_seconds <
    20.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_takeoff_cooldown_interval_seconds <
    90.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_takeoff_energyRequired_factors <
    10000.0
    10.0
    100.0
    0.0
    0.0
    >
    D:planet_takeoff_max_jump_distance <
    50.0
    0.1
    0.0
    0.0
    0.0
    >
    D:planet_takeoff_sickness_seconds <
    0.0
    0.0
    0.0
    0.0
    0.0
    >
    D:planet_takeoff_warmup_seconds <
    20.0
    0.0
    0.0
    0.0
    0.0
    >
    D:space_moving_cooldown_interval_seconds <
    30.0
    0.0
    0.0
    0.0
    0.0
    >
    D:space_moving_energyRequired_factors <
    1000.0
    10.0
    100.0
    0.0
    0.0
    >
    D:space_moving_max_jump_distance <
    100.0
    0.1
    0.0
    0.0
    0.0
    >
    D:space_moving_sickness_seconds <
    0.0
    0.0
    0.0
    0.0
    0.0
    >
    D:space_moving_warmup_seconds <
    10.0
    0.0
    0.0
    0.0
    0.0
    >
}


    ship_scanner {
    I:deploy_blocks_per_interval=10
    I:deploy_interval_ticks=4
    I:max_deploy_radius_blocks=100
    I:scan_blocks_per_second=10
    I:search_interval_ticks=20
}


    tooltip {
    S:add_armor_points=NEVER
    S:add_block_material=ADVANCED_TOOLTIPS
    S:add_burn_time=ADVANCED_TOOLTIPS
    S:add_durability=ALWAYS
    S:add_enchantability=ON_SNEAK
    S:add_entity_id=ADVANCED_TOOLTIPS
    S:add_flammability=ADVANCED_TOOLTIPS
    S:add_fluid_stats=ALWAYS
    S:add_hardness=ADVANCED_TOOLTIPS
    S:add_harvesting_stats=ALWAYS
    S:add_opacity=ADVANCED_TOOLTIPS
    S:add_ore_dictionary_name=ALWAYS
    S:add_registry_name=ADVANCED_TOOLTIPS
    S:add_repair_material=ON_SNEAK
    S:cleanup_list <
    fuel details
    burn time
    durability
    >
    S:enable_deduplication=ALWAYS
}


    transporter {
    I:max_energy_stored=1000000
}


    tree_farm {
    I:max_mediums_count=5
    I:max_radius_no_laser_medium=3
    I:max_radius_per_laser_medium=2
    I:max_reach_distance_no_laser_medium=8
    I:max_reach_distance_per_laser_medium=6
}


